export { cartReducer } from './cart.reducer'
export { filterReducer } from './filters.reducer'
export { productsReducer } from './products.reducer'
export { signupFormReducer } from './signup.reducer'
export { loginFormReducer } from './login.reducer'
export { wishlistReducer } from './wishlist.reducer'