export const getBgColor = (theme) => theme === 'light' ? 'bg-primary' : 'bg-secondary'
export const getTextColor = (theme) => theme === 'light' ? 'txt-primary' : 'txt-secondary'
export const getSolidBtnBgColor = (theme) => theme === 'dark' ? 'bg-primary' : 'bg-secondary'
export const getSolidBtnTextColor = (theme) => theme === 'dark' ? 'txt-primary' : 'txt-secondary'
export const getBorderColor = (theme) => theme === 'light' ? 'b-primary' : 'b-secondary'
